CHANGELOG.md, setup.py
=> Bump version to 1.1.0

README.rst, qingstor/qsctl/commands/base.py, qingstor/qsctl/commands/ls.py, qingstor/qsctl/commands/transfer.py, tests/commands/test_transfer.py, tests/test_data_example.py
- tests: Update test_data_example to new schema
- Fix bug that list_keys do not respect prefix
- docs: Fix typo in readme
- Fix empty output while access_key_id is invalid
- style: Format code with google style
=> Fix list_keys do not respect prefix && empty output while access_key_id is invalid

CHANGELOG.md, setup.py
=> Bump to version 1.2.0

CHANGELOG.md, setup.py
=> Bump to version 1.2.1

CHANGELOG.md, setup.py
=> Bump to version 1.2.2

CHANGELOG.md, setup.py
=> Bump to version 1.2.3

CHANGELOG.md, setup.py
=> Bump to version 1.3.0

qingstor/qsctl/commands/transfer.py
=> Fix bug in sync command

CHANGELOG.md, setup.py
=> Bump to version 1.3.1

CHANGELOG.md, setup.py
=> Bump to version 1.4.0

qingstor/qsctl/commands/transfer.py, qingstor/qsctl/compat.py, qingstor/qsctl/utils.py, tox.ini
=> Fix tqdm encoding error on python2.6

CHANGELOG.md, setup.py
=> Bump to version 1.4.1

Makefile, appveyor.yml, qingstor/qsctl/commands/base.py
-Add a feature to generate a gzip file for offline installation
=> Add offline-package to Makefile

qingstor/qsctl/commands/base.py, qingstor/qsctl/commands/ls.py, qingstor/qsctl/commands/mb.py, qingstor/qsctl/commands/presign.py, qingstor/qsctl/commands/rb.py, qingstor/qsctl/commands/rm.py, qingstor/qsctl/commands/sync.py, qingstor/qsctl/commands/transfer.py
I'm sorry for merging the branch, so I made a new pr.
=> Modify current_bucket to variable of class

action/bucket.go, action/bucket_test.go, action/ls.go, action/ls_test.go, action/utils_test.go, cmd/init.go, cmd/ls.go, constants/errors.go, constants/time.go, constants/types.go, contexts/contexts.go, main.go, storage/interface.go, storage/mock.go, storage/qingstor.go, utils/convert.go, utils/convert_test.go, utils/print.go, utils/print_test.go
cmd/ls: Add ls command, bucket acl interface and relevant convert, align func for printing
=> cmd/ls: Add ls command

action/presign.go, action/presign_test.go, cmd/qsctl/cp.go, cmd/qsctl/init.go, cmd/qsctl/presign.go, cmd/qsctl/tee.go, constants/errors.go, constants/flags.go, constants/name.go, constants/types.go, storage/interface.go, storage/mock.go, storage/qingstor.go
cmd/presign: Add presign and unit tests
=> Add presign

cmd/qsctl/cp.go, cmd/qsctl/init.go, cmd/qsctl/ls.go, cmd/qsctl/rb.go, cmd/qsctl/tee.go, task/common/bucket.go, task/common/bucket_generated.go, task/common/bucket_generated_test.go, task/common/bucket_test.go, task/common/multipart.go, task/common/multipart_generated.go, task/common/multipart_generated_test.go, task/common/multipart_test.go, task/copy_file.go, task/copy_generated_test.go, task/copy_stream.go, task/list_generated_test.go, task/make_bucket_generated_test.go, task/presign_generated_test.go, task/remove_bucket.go, task/remove_bucket_generated_test.go, task/remove_bucket_test.go, task/remove_object_generated_test.go, task/stat_generated_test.go, task/tasks.json, task/tasks_gen.go, utils/random_test.go, utils/task.go
This PR will:
Add feature rb -f
Modify dependent task test template, add test for Wait
=> Feature rb -f

cmd/qsctl/cat_test.go, cmd/qsctl/taskutils/progress.go, cmd/qsctl/taskutils/progress_test.go, cmd/qsctl/taskutils/tasks_test.go, utils/print_test.go, utils/task_test.go, utils/work_dir_test.go
Add unit tests for utils, and fix a bug which triggers data race in progress.
=> Add unit tests

cmd/qsctl/ls.go, go.mod, go.sum
=> cmd/ls: Format ls style

CHANGELOG.md, constants/version.go
=> Bump to version 2.2.0

CHANGELOG.md, constants/version.go
=> Bump to version 2.4.2

Makefile
=> build: Use static build via cgo disabled

CHANGELOG.md, constants/version.go
Signed-off-by: Prnyself <281239768@qq.com>
=> Bump to version 2.4.3

nfpm.yaml
Signed-off-by: Prnyself <281239768@qq.com>
=> Bump nfpm version to 2.4.3

CHANGELOG.md, constants/version.go, nfpm.yaml
- feat: Added support for virtual host style (#390)
=> Bump to version 2.4.6

nfpm.yaml
The previous document links has expred
=> Updated the official document links
